### ISSUE TITLE
script returning errors

### ISSUE THREAD

**Issue by ghost** [sritchie73/liftOverPlink#1]

**Comment by sritchie73** [comment]
Hi yorgos-a, can you provide more information about the errors the script is returning? It's been a while since I used the script, but to my knowledge it was working when I published it on github.

**Comment by ghost** [comment]
Dear Scott,

Major apologies for the post. At a later stage I noticed that the error I
was receiving was because I had to change the permissions on your script.
After that, it worked like a chant.

Please feel free to remove my error message from your page (I tried to do
it but I couldn't find how).

Thanks for the very handy code! It saved me tons of work!

All the best,

Yorgos

On 22 December 2014 at 03:56, Scott Ritchie notifications@github.com
wrote:

> Hi yorgos-a, can you provide more information about the errors the script
> is returning? It's been a while since I used the script, but to my
> knowledge it was working when I published it on github.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sritchie73/liftOverPlink/issues/1#issuecomment-67797366
> .

## 

Georgios Athanasiadis, PhD
Bioinformatics Research Center
C.F. Møllers Alle, Building 1110
&
Centre for Biocultural History
Jens Chr. Skous Vej 7
Aarhus University
8000 Aarhus C (Denmark)

Handling editor at BMC Journal of Biological Research
http://www.jbiolres.com/
